### ISSUE TITLE
Plot velocity and depth time series for problematic spots when the model have multiple domains 

### ISSUE THREAD

**Issue by mohamedmorsy** [Dewberry/hecrasio#10]
Please check if the code loop through all the model domains (not only one domain)  and identify any high velocities.

**Comment by johnwallx** [comment]
This is still being carried out in the `QAQC-FluvialTest` notebook, but does not get executed for pluvial. Not sure why this is the case. Notes within `velCheckMain` suggest something was not executing under a particular circumstance.

Pinging @slawler for insight.

**Comment by slawler** [comment]
Resolved in PR #15
