### ISSUE TITLE
Create AOIs for mini-map more easily from results

### ISSUE THREAD

**Issue by mohamedmorsy** [Dewberry/hecrasio#6]
figure out how to pull domain extents using pluvial model output as an example.

**Comment by johnwallx** [comment]
This issue is being resolved by branch `hot-fix/single-vs-list` along with issues #7, #9

**Comment by johnwallx** [comment]
Okay, `plot_extreme_edges` needs to be updated with a `**kwargs`.

**Comment by slawler** [comment]
Resolved in PR #15
