### ISSUE TITLE
Histogram for hydromerological time steps

### ISSUE THREAD

**Issue by mohamedmorsy** [Dewberry/hecrasio#8]
Currently, we plot the precipitation data as continuous data. We need to plot it as a histogram.

![image](https://user-images.githubusercontent.com/5543781/63192512-42ece100-c039-11e9-8a34-73e994179fd6.png)

**Comment by slawler** [comment]
This feature was added to pfra-hydromet [98cb85f](https://github.com/Dewberry/pfra-hydromet/commit/98cb85f4b68c88c037c04d76594a7183c78efb47). Closing this issue here, if we want to implement in hecrasio code can be copied and integrated with a feature-request PR.
