### ISSUE TITLE
Plot the water depth for all model domains

### ISSUE THREAD

**Issue by mohamedmorsy** [Dewberry/hecrasio#9]
Currently, if we have a model with multiple domains, we plot the water depth for one domain only.

![image](https://user-images.githubusercontent.com/5543781/63193393-5b5dfb00-c03b-11e9-8201-682cfc947086.png)

![image](https://user-images.githubusercontent.com/5543781/63193417-6add4400-c03b-11e9-9c62-f392a11b1435.png)

**Comment by johnwallx** [comment]
Using a for-loop and try-except resolve this.

**Comment by slawler** [comment]
Resolved in PR #15
